version: '3'

services:
  org-lookup-orchestrator:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8080:8080
    environment:
      
    entrypoint: sh -ce "./check_node_modules.sh && npm run build && npm run start"
    volumes:
      - .:/org-lookup-orchestrator
    tty: true

