version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8080:8080
    entrypoint: sh -ce "./check_node_modules.sh && npm run start-dev"
    volumes:
      - .:/project
    tty: true

