version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8080:8080
    entrypoint: sh -ce "./check_node_modules.sh && npm run dev:watch"
    environment:
      REDIS_URL: "${REDIS_URL}"
      PNO_SERVICE_URL: "${PNO_SERVICE_URL}"
    volumes:
      - .:/project
    depends_on:
      - redis
    tty: true
  redis:
    image: 'redis:alpine'
    ports:
      - 6379:6379
