version: 2.1

orbs:
  ci: kwri/ci@1
  coveralls: coveralls/coveralls@1.0.6

workflows:
  build-push:
    jobs:
      - ci/build-push:
          context: nonprod_push_and_deploy
          git-branch: << pipeline.git.branch >>
          service: connect-org-lookup-orchestrator
          platform: connect
      - ci/tag:
          context: nonprod_push_and_deploy
          service: connect-org-lookup-orchestrator
          requires:
            - ci/build-push
          filters:
            branches:
              only:
                - main
      - unit_test:
          context: nonprod_push_and_deploy
          requires:
            - ci/build-push
          filters:
            branches:
              ignore:
                - main

jobs:
  unit_test:
    working_directory: /usr/src/app
    executor:
      name: ci/test
      service: connect-org-lookup-orchestrator
    steps:
      - run:
          name: Run Unit Tests
          command: |
            yarn run test:ci
          no_output_timeout: 10m
      - store_test_results:
          path: coverage
      - store_artifacts:
          path: coverage
      - coveralls/upload
