services:
  - routes:
      - attributes:
          methods:
            - OPTIONS
            - GET
            - POST
            - PUT
            - PATCH
            - DELETE
          paths:
            - /connect-org-lookup-orchestrator
    attributes:
      url: http://$upstream_host/
    plugins: []
    name: connect-org-lookup-orchestrator
  - routes:
      - attributes:
          methods:
            - OPTIONS
            - GET
          paths:
            - /connect-org-lookup-orchestrator/health
    attributes:
      url: http://$upstream_host/health
    plugins: []
    name: connect-org-lookup-orchestrator.health
plugins: []
consumers:
  - acls: []
    credentials: []
    custom_id: '0'
    username: anonymous